// components/home/mockData.ts
// TODO: DELETE this file and remove its import from index.tsx once real data is confirmed working.

import { Novel, Advertisement } from '@/types/home';

export const MOCK_CONTINUE_READING: Novel[] = [
  {
    id: 'mock-cr-1',
    title: 'The Kingdom of Copper',
    author: 'S.A. Chakraborty',
    description: 'A sweeping fantasy epic.',
    category: 'Fantasy',
    cover_image_url: 'https://covers.openlibrary.org/b/id/10909258-L.jpg',
    rating: 4.4,
    total_ratings: 18200,
    views: 94000,
    tags: [
      { id: 't1', name: 'Epic Fantasy', slug: 'epic-fantasy', category: 'Fantasy' },
      { id: 't2', name: 'Dark Fantasy', slug: 'dark-fantasy', category: 'Fantasy' },
    ],
    reading_progress: { progress_percentage: 38, current_page: 152 },
  },
  {
    id: 'mock-cr-2',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    description: 'A shocking psychological thriller.',
    category: 'Thriller',
    cover_image_url: 'https://covers.openlibrary.org/b/id/9256866-L.jpg',
    rating: 4.2,
    total_ratings: 42000,
    views: 210000,
    tags: [
      { id: 't3', name: 'Psychological', slug: 'psychological', category: 'Thriller' },
    ],
    reading_progress: { progress_percentage: 72, current_page: 288 },
  },
  {
    id: 'mock-cr-3',
    title: 'Icebreaker',
    author: 'Hannah Grace',
    description: 'A college sports romance.',
    category: 'Romance',
    cover_image_url: 'https://covers.openlibrary.org/b/id/12547191-L.jpg',
    rating: 4.1,
    total_ratings: 31000,
    views: 158000,
    tags: [
      { id: 't4', name: 'Slow Burn', slug: 'slow-burn', category: 'Romance' },
    ],
    reading_progress: { progress_percentage: 15, current_page: 60 },
  },
];

export const MOCK_NOVELS_BY_CATEGORY: Record<string, Novel[]> = {
  Romance: [
    {
      id: 'mock-rom-1',
      title: 'The Love Hypothesis',
      author: 'Ali Hazel',
      description: 'A fake dating romance between a PhD student and her professor.',
      category: 'Romance',
      cover_image_url: 'https://covers.openlibrary.org/b/id/12006049-L.jpg',
      rating: 4.0,
      total_ratings: 58000,
      views: 320000,
      tags: [{ id: 't5', name: 'Slow Burn', slug: 'slow-burn', category: 'Romance' }],
    },
    {
      id: 'mock-rom-2',
      title: 'It Ends with Us',
      author: 'Colleen Hoover',
      description: 'A brave and heartbreaking love story.',
      category: 'Romance',
      cover_image_url: 'https://covers.openlibrary.org/b/id/10909047-L.jpg',
      rating: 4.5,
      total_ratings: 120000,
      views: 700000,
      tags: [{ id: 't6', name: 'Dark Romance', slug: 'dark-romance', category: 'Romance' }],
    },
    {
      id: 'mock-rom-3',
      title: 'Beach Read',
      author: 'Emily Henry',
      description: 'Two writers swap genres for the summer.',
      category: 'Romance',
      cover_image_url: 'https://covers.openlibrary.org/b/id/10521352-L.jpg',
      rating: 4.1,
      total_ratings: 44000,
      views: 230000,
      tags: [{ id: 't5', name: 'Slow Burn', slug: 'slow-burn', category: 'Romance' }],
    },
    {
      id: 'mock-rom-4',
      title: 'People We Meet on Vacation',
      author: 'Emily Henry',
      description: 'Best friends who travel together every summer.',
      category: 'Romance',
      cover_image_url: 'https://covers.openlibrary.org/b/id/11386095-L.jpg',
      rating: 4.2,
      total_ratings: 51000,
      views: 270000,
      tags: [{ id: 't4', name: 'Second Chance', slug: 'second-chance', category: 'Romance' }],
    },
  ],
  Fantasy: [
    {
      id: 'mock-fan-1',
      title: 'A Court of Thorns and Roses',
      author: 'Sarah J. Maas',
      description: 'A human girl is taken to a dangerous magical land.',
      category: 'Fantasy',
      cover_image_url: 'https://covers.openlibrary.org/b/id/9253618-L.jpg',
      rating: 4.3,
      total_ratings: 97000,
      views: 510000,
      tags: [{ id: 't2', name: 'Romantasy', slug: 'romantasy', category: 'Fantasy' }],
    },
    {
      id: 'mock-fan-2',
      title: 'The Name of the Wind',
      author: 'Patrick Rothfuss',
      description: 'The tale of a magically gifted young man.',
      category: 'Fantasy',
      cover_image_url: 'https://covers.openlibrary.org/b/id/7984916-L.jpg',
      rating: 4.5,
      total_ratings: 83000,
      views: 430000,
      tags: [{ id: 't1', name: 'Epic Fantasy', slug: 'epic-fantasy', category: 'Fantasy' }],
    },
    {
      id: 'mock-fan-3',
      title: 'Fourth Wing',
      author: 'Rebecca Yarros',
      description: 'A war college for dragon riders.',
      category: 'Fantasy',
      cover_image_url: 'https://covers.openlibrary.org/b/id/13183330-L.jpg',
      rating: 4.4,
      total_ratings: 74000,
      views: 390000,
      tags: [{ id: 't2', name: 'Romantasy', slug: 'romantasy', category: 'Fantasy' }],
    },
    {
      id: 'mock-fan-4',
      title: 'The Way of Kings',
      author: 'Brandon Sanderson',
      description: 'A world of storms and ancient powers.',
      category: 'Fantasy',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8739161-L.jpg',
      rating: 4.7,
      total_ratings: 110000,
      views: 580000,
      tags: [{ id: 't1', name: 'Epic Fantasy', slug: 'epic-fantasy', category: 'Fantasy' }],
    },
  ],
  Mystery: [
    {
      id: 'mock-mys-1',
      title: 'The Girl with the Dragon Tattoo',
      author: 'Stieg Larsson',
      description: 'A journalist investigates a decades-old disappearance.',
      category: 'Mystery',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8479576-L.jpg',
      rating: 4.3,
      total_ratings: 88000,
      views: 450000,
      tags: [{ id: 't7', name: 'Crime Thriller', slug: 'crime-thriller', category: 'Mystery' }],
    },
    {
      id: 'mock-mys-2',
      title: 'Gone Girl',
      author: 'Gillian Flynn',
      description: 'A wife goes missing on her anniversary.',
      category: 'Mystery',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8226100-L.jpg',
      rating: 4.0,
      total_ratings: 95000,
      views: 520000,
      tags: [{ id: 't3', name: 'Psychological', slug: 'psychological', category: 'Mystery' }],
    },
    {
      id: 'mock-mys-3',
      title: 'In the Woods',
      author: 'Tana French',
      description: 'A detective returns to a scene from his past.',
      category: 'Mystery',
      cover_image_url: 'https://covers.openlibrary.org/b/id/7886094-L.jpg',
      rating: 4.1,
      total_ratings: 33000,
      views: 170000,
      tags: [{ id: 't8', name: 'Whodunit', slug: 'whodunit', category: 'Mystery' }],
    },
  ],
  'Sci-Fi': [
    {
      id: 'mock-sci-1',
      title: 'Dune',
      author: 'Frank Herbert',
      description: 'The story of a desert planet and its precious resource.',
      category: 'Sci-Fi',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8689556-L.jpg',
      rating: 4.6,
      total_ratings: 130000,
      views: 690000,
      tags: [{ id: 't9', name: 'Space Opera', slug: 'space-opera', category: 'Sci-Fi' }],
    },
    {
      id: 'mock-sci-2',
      title: 'The Martian',
      author: 'Andy Weir',
      description: 'An astronaut stranded alone on Mars.',
      category: 'Sci-Fi',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8739028-L.jpg',
      rating: 4.5,
      total_ratings: 76000,
      views: 400000,
      tags: [{ id: 't10', name: 'Survival', slug: 'survival', category: 'Sci-Fi' }],
    },
    {
      id: 'mock-sci-3',
      title: 'Project Hail Mary',
      author: 'Andy Weir',
      description: 'A lone astronaut must save Earth.',
      category: 'Sci-Fi',
      cover_image_url: 'https://covers.openlibrary.org/b/id/12187770-L.jpg',
      rating: 4.8,
      total_ratings: 68000,
      views: 360000,
      tags: [{ id: 't9', name: 'Space Opera', slug: 'space-opera', category: 'Sci-Fi' }],
    },
  ],
  Thriller: [
    {
      id: 'mock-thr-1',
      title: 'The Silent Patient',
      author: 'Alex Michaelides',
      description: 'A famous painter shoots her husband and never speaks again.',
      category: 'Thriller',
      cover_image_url: 'https://covers.openlibrary.org/b/id/9256866-L.jpg',
      rating: 4.2,
      total_ratings: 42000,
      views: 210000,
      tags: [{ id: 't3', name: 'Psychological', slug: 'psychological', category: 'Thriller' }],
    },
    {
      id: 'mock-thr-2',
      title: 'The Da Vinci Code',
      author: 'Dan Brown',
      description: 'A murder in the Louvre reveals a secret society.',
      category: 'Thriller',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8110130-L.jpg',
      rating: 3.9,
      total_ratings: 140000,
      views: 750000,
      tags: [{ id: 't11', name: 'Spy Thriller', slug: 'spy-thriller', category: 'Thriller' }],
    },
  ],
  Horror: [
    {
      id: 'mock-hor-1',
      title: 'The Shining',
      author: 'Stephen King',
      description: 'A family becomes caretakers of an isolated hotel.',
      category: 'Horror',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8231462-L.jpg',
      rating: 4.4,
      total_ratings: 89000,
      views: 470000,
      tags: [{ id: 't12', name: 'Supernatural', slug: 'supernatural', category: 'Horror' }],
    },
    {
      id: 'mock-hor-2',
      title: 'IT',
      author: 'Stephen King',
      description: 'A shape-shifting evil terrorises a small town.',
      category: 'Horror',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8091016-L.jpg',
      rating: 4.3,
      total_ratings: 74000,
      views: 390000,
      tags: [{ id: 't12', name: 'Supernatural', slug: 'supernatural', category: 'Horror' }],
    },
  ],
  Adventure: [
    {
      id: 'mock-adv-1',
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      description: 'A shepherd boy journeys to find treasure.',
      category: 'Adventure',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8709895-L.jpg',
      rating: 4.1,
      total_ratings: 110000,
      views: 600000,
      tags: [{ id: 't13', name: 'Historical', slug: 'historical', category: 'Adventure' }],
    },
    {
      id: 'mock-adv-2',
      title: 'Into the Wild',
      author: 'Jon Krakauer',
      description: 'A young man abandons society to live in the Alaskan wilderness.',
      category: 'Adventure',
      cover_image_url: 'https://covers.openlibrary.org/b/id/8109887-L.jpg',
      rating: 4.0,
      total_ratings: 45000,
      views: 230000,
      tags: [{ id: 't14', name: 'Survival', slug: 'survival', category: 'Adventure' }],
    },
  ],
};

export const MOCK_ADS: Advertisement[] = [
  {
    id: 'mock-ad-1',
    image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=400&fit=crop',
    title: 'Discover Fantasy Worlds',
    subtitle: 'Hundreds of epic adventures waiting',
    link_type: 'category',
    link_value: 'Fantasy',
    sort_order: 1,
  },
  {
    id: 'mock-ad-2',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&h=400&fit=crop',
    title: 'New Romance Arrivals',
    subtitle: 'Fall in love with a new story',
    link_type: 'category',
    link_value: 'Romance',
    sort_order: 2,
  },
  {
    id: 'mock-ad-3',
    image_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=400&fit=crop',
    title: 'Top Mystery Picks',
    subtitle: 'Can you solve the case?',
    link_type: 'category',
    link_value: 'Mystery',
    sort_order: 3,
  },
];